#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

commit_msg_file="$1"
commit_msg=$(cat "$commit_msg_file")
regex_pattern="^(fix|feat|docs|chore|refactor)(-#[0-9]+)?: .+\$"
if [[ $commit_msg =~ $regex_pattern ]]; then
  echo ""
  echo "Hey, hurrah! Thank you for giving attention and following our community guidelines."
  echo "We're excited to merge your code into the project!"
  echo ""
else
  echo ""
  echo "Oops!! It seems like you haven't read our community guidelines yet!!"
  echo "Commits can be of form:"
  echo ""
  echo "<tag>-#<issue number>: <commit message>   # if you have relevant issue"
  echo "OR"
  echo "<tag>: <commit message>                   # if you don't have relevant issue"
  echo ""
  echo "Examples:"
  echo "❌ Fixed a bug"
  echo "✅ fix-#123: Fixed a bug"
  echo "❌ Updated documentation file"
  echo "✅ chore: Updated documentation"
 
  echo ""
  echo "To know all the available tags and for more details"
  echo "Kindly refer to \033]8;;https://github.com/krishnaacharyaa/wanderlust/blob/9b11b769bb23150b746296cf9008056633d21921/.github/CONTRIBUTING.md#guidelines-for-contributions\aContributing Guidelines\033]8;;\a."
  echo ""
exit 1
fi