#!/usr/bin/env sh
chmod ug+x .husky/*
chmod ug+x .git/hooks/*

. "$(dirname -- "$0")/_/husky.sh"

cd frontend
echo [FRONTEND] Running the prettier format for you.
npx lint-staged

cd ../backend
echo [BACKEND] Running the prettier format for you
npx lint-staged